### ISSUE TITLE
Add Association Name parameter to ExecuteInterface_Delimited_4_1_00 Java action

### ISSUE THREAD

**Issue by martin-de-heer** [Erwin-t-Hoen/Flat-File-Importer#8]
In previous versions it was possible to pass an "Association name" parameter when using the ExecuteInterface_Delimited_4_1_00 Java action. This would associate all the newly created objects to an already existing object (for instance the original file object). This was handy for retrieving the objects afterwards. In the latest version (7.1.0) this parameter is missing. Could you please bring it back?

Thanks for this great module!

**Comment by Erwin-t-Hoen** [comment]
As far as I can see this option was not present in the version before 7.1.0
Could it be that you have added this in your specific project?
Would be a nice addition to the module and I'll keep it in mind for a future release.
As this is a feature request rather than an issue I'll close this issue for now.
