### ISSUE TITLE
Process files with different number of columns with the same definition.

### ISSUE THREAD

**Issue by YasmijnNL** [Erwin-t-Hoen/Flat-File-Importer#9]
In previous versions it was possible to process files with different number of columns with the same interface definition. It looks like non-existing columns were added before processing.

In newer versions this doesn't work anymore, which is causing us a lot of remodelling.
It would be awesome if the option to process files with different nr of columns in the same interface definition again.

**Comment by Erwin-t-Hoen** [comment]
YasmijnNL, I do not recall this option.
The amount of columns needed to match the file to be imported.
Maybe this was something created in a specific project or else please provide me with an example of this functionality. For now I'll close this issue as it seems to be a request for a feature rather than an issue. But if I'm mistaken please set me right!
